title: Welcome to Yujia's Portfolio
description: recording of my growing path...
theme: just-the-docs

url: https://yujia-ma-ucl.github.io/Yujia-s-Profile

aux_links:
  Template Repository: https://github.com/yujia-ma-ucl.github.io/Yujia-s-Profile
