title: Yujia's Portfolio
description: recording of my growing path...
theme: just-the-docs

url: https://yujia-ma-ucl.github.io/Yujia-s-Profile

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      
aux_links:
  Template Repository: https://github.com/yujia-ma-ucl.github.io/Yujia-s-Profile
